### ISSUE TITLE
KB4016240 breaks Shrew Reconnect

### ISSUE THREAD

**Issue by JaredEStoddard** [CamW/shrew-reconnect#5]
Cumulative Update for Windows 10 Version 1703 for x64-based Systems (KB4016240)

Application: ShrewReconnect.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Windows.Forms.Control.MarshaledInvoke(System.Windows.Forms.Control, System.Delegate, System.Object[], Boolean)
   at System.Windows.Forms.Control.Invoke(System.Delegate, System.Object[])
   at com.waldron.shrewReconnect.MainForm.notifications_OperationLogged(System.Object, com.waldron.shrewReconnect.Shrew.OperationLogArgs)
   at com.waldron.shrewReconnect.Shrew.ShrewNotifier.Log(System.String, com.waldron.shrewReconnect.Shrew.ShrewConnectionStatus)
   at com.waldron.shrewReconnect.DaemonUtils.checkDaemon(System.String)
   at com.waldron.shrewReconnect.ShrewConnection.ConnectProcess()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

Faulting application name: ShrewReconnect.exe, version: 1.0.7.0, time stamp: 0x58033afd
Faulting module name: KERNELBASE.dll, version: 10.0.15063.0, time stamp: 0x461a0ff5
Exception code: 0xe0434352
Fault offset: 0x0000000000069e08
Faulting process id: 0x17fc
Faulting application start time: 0x01d2c8df27f8523c
Faulting application path: C:\Program Files\Cameron Waldron\Shrew VPN Reconnect\ShrewReconnect.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 6f8f375c-0eea-49f8-af7c-dfeabdede262
Faulting package full name: 
Faulting package-relative application ID:

**Comment by JaredEStoddard** [comment]
Error in source: "Invoke or BeginInvoke cannot be called on a control until the window handle has been created."  Got source to run (for my purposes) by adding try/catch (empty) in MainForm.cs/**notifications_OperationLogged**.

**Comment by darkdevil1** [comment]
Confirmed, same problem here on Server 2016.

**Comment by CamW** [comment]
Fixed in v1.0.8
